config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'trips#index'

  resources :trips

  resources :locations do
    resources :addresses
  end

  get '/trip/:id/find_location/:id', to: 'trips#find_location', as: 'find_location'
  patch '/trip/:id/add_location/', to: 'trips#add_location', as: 'add_location'
  patch '/trip/:id/remove_location/:trip_id', to: 'trips#remove_location', as: 'remove_location'

end

app/models/trip.rb
# == Schema Information
#
# Table name: trips
#
#  id                 :integer          not null, primary key
#  name               :string           not null
#  date_start         :date             not null
#  date_end           :date             not null
#  user_id            :integer
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  image_file_name    :string
#  image_content_type :string
#  image_file_size    :integer
#  image_updated_at   :datetime
#  desc               :text
#
# Indexes
#
#  index_trips_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#

class Trip < ApplicationRecord
  belongs_to :user
  has_many :locations, dependent: :destroy
  has_attached_file :image, optional: true
  validates_attachment :image,
                     content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

  def check_date_closeness
    time_away_in_days = (self.date_start - DateTime.now).to_i

    if time_away_in_days > 7
      "#{time_away_in_days} days until your trip!"
    elsif time_away_in_days > 0 && time_away_in_days <= 7
      "#{time_away_in_days} days until your trip! Better start packing!"
    else
      "We hope you enjoyed your trip!"
    end

  end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_trip, only: [:show, :edit, :update, :destroy, :find_location, :add_location, :remove_location]

  def index
    @trips = current_user.trips
  end

  def show
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = current_user.trips.create(trip_params)
    if @trip.save
      redirect_to trips_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @trip.update(trip_params)
      redirect_to trip_path(@trip)
    else
      render 'edit'
    end
  end

  def destroy
    @trip.destroy
    redirect_to trips_path
  end


  def find_location
    @locations = Location.find_location_not_on_trip
  end

  def add_location
    @location = Location.find(params[:format])
    @location.update(trip_id: params[:id])
    redirect_to trip_path(@trip)
  end

  def remove_location
    @location = Location.find(params[:trip_id])
    @location.update(trip_id: nil)
    redirect_to trip_path(@trip)
  end

  private

  def set_trip
    @trip = current_user.trips.find(params[:id])
  end

  def trip_params
    params.require(:trip).permit(:name, :date_start, :date_end, :image, :desc)
  end

end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_form.html.erb
<h1><%= @trip.id? ? 'Edit' : 'Create' %></h1>
<div class="ui divider"></div>

<%= form_for @trip, html: {class: "ui form"} do |f| %>

  <div class="eight wide field">
    <p><strong><%= f.label :name %></strong></p>
    <%= f.text_field :name, required: true %>
  </div>


  <div class="fields">
    <div class="four wide field">
      <p><strong><%= f.label :date_start %></strong></p>
      <%= f.date_field :date_start, required: true %>
    </div>
    <div class="four wide field">
      <p><strong><%= f.label :date_end %></strong></p>
      <%= f.date_field :date_end, required: true %>
    </div>
  </div>

  <div class="eight wide field">
    <p><strong><%= f.label :description %></strong></p>
    <%= f.text_area :desc %>
  </div>

  <div class="four wide field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="ui hidden divider"></div>

  <div class="action">
    <%= f.submit class: 'ui teal button' %>
  </div>


  <div class="ui hidden divider"></div>

<% end %>

<% if @trip.id? %>
  <%= link_to 'Cancel', trip_path(@trip), class: 'ui red button' %>
<% else %>
  <%= link_to 'Cancel', trips_path, class: 'ui red button' %>
<% end %>

app/views/trips/find_location.html.erb
<div class="ui grid">
  <div class "sixteen wide computer column">
    <div class="ui cards">
      <% @locations.each do |location| %>
        <div class="card">
          <div class="image">
            <%= check_if_image_is_present(location) %>
          </div>
          <div class="content">
            <div class="ui center aligned">
              <p><strong><%= location.name %></strong></p>
            </div>
          </div>
          <div class="extra content">
            <%= link_to 'Add to Trip', add_location_path(@trip, location), method: :patch, class: 'ui green button' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/trips/index.html.erb
<header id="welcome">
  <h1>Welcome back,&ensp;<%= current_user.first_name %></h1>
  <h3> <%= DateTime.now.strftime('%A, %B %e, %Y') %> </h3>
</header>

<h2>Your trips&ensp;<%= link_to 'Add a Trip', new_trip_path, class: 'ui small teal button' %></h2>

<div class="ui divider hidden"></div>

<div class="ui grid">
    <div class "sixteen wide computer column">
      <div class="ui cards">
        <% @trips.each do |trip| %>
          <div class="card">
            <div class="image">
              <%= check_if_image_is_present(trip) %>
            </div>
            <div class="content">
              <div class="header">
                <%= link_to trip.name, trip_path(trip.id), class: 'header', data: { turbolinks: false } %>
                <br>
              </div>
              <p><%= trip.check_date_closeness %></p>
              <div class="ui divider"></div>
              <div class="ui center aligned">
                <em><%= display_date_range(trip) %></em>
              </div>
            </div>
            <div class="extra content">
              <%= link_to 'Preview', trip_path(trip.id), class: 'ui orange button', data: { turbolinks: false } %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/trips/new.html.erb
<%= render 'form' %>

app/views/trips/show.html.erb
<header id="welcome">
  <h1>Your <%= @trip.name %> Trip</h1> <%= display_date_range(@trip) %> (<%= (@trip.date_end - @trip.date_start).to_i %> days)
</header>

<br>

<%= link_to 'Edit', edit_trip_path, class: 'ui teal button' %>
<%= link_to 'Remove Trip', trip_path(@trip), method: :delete, data: { confirm: 'Are you sure?'}, class: 'ui red button' %>
<%= link_to 'Add New Location', find_location_path, class: 'ui orange button' %>

<div class="ui piled segment">
  <p><%= @trip.desc %></p>
</div>

<div class="ui divider hidden"></div>

<div class="ui grid">
  <div class "eight wide computer column">
    <div class="ui cards">
      <% if @trip.locations.any? %>
        <% @trip.locations.each do |location| %>
          <div class="card">
            <div class="image">
              <%= check_if_image_is_present(location) %>
            </div>
            <div class="content">
              <div class="ui center aligned">
                <strong><%= location.name %></strong>
                <br>
                <% unless location.address == nil %>
                  <em><%= display_full_address(location) %></em>
                <% end %>
              </div>
            </div>
            <div class="extra content">
              <%= link_to 'Remove Location', remove_location_path(@trip, location), method: :patch, class: 'ui red button' %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="eight wide computer column">
    <div style='width: 500px;'>
      <div id="map" style='width: 500px; height: 250px;'></div>
    </div>
  </div>
</div>

<%= render 'shared/map' %>