config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'trips#index'

  resources :trips

  resources :locations do
    resources :addresses
  end

  get '/trip/:id/find_location/:id', to: 'trips#find_location', as: 'find_location'
  patch '/trip/:id/add_location/', to: 'trips#add_location', as: 'add_location'
  patch '/trip/:id/remove_location/:trip_id', to: 'trips#remove_location', as: 'remove_location'

end

app/views/shared/_footer.html.erb
<footer>
  <div class="ui bottom inverted menu ui grid">
    <div class="four column row">
      <div class="column">
        <p>© 2017 TravelTrackr</p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_map.html.erb
<script src="//maps.google.com/maps/api/js?key=AIzaSyACv0HxzgtOKkvBnnX1Y-5p1OGVQYVGEc4"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>

<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.map.centerOn({ lat: 40.761215, lng: -111.882853 })
    handler.fitMapToBounds();
    handler.getMap().setZoom(6);
  });
</script>

app/views/shared/_nav.html.erb
<div class="ui inverted menu">
  <div id="brand" class="item">TripTrackr</div>
  <% if user_signed_in? %>
    <%= link_to 'Trips', trips_path, class: 'item' %>
    <%= link_to 'Destinations', locations_path, class: 'item' %>
    <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'right item' %>
  <% else %>
    <%= link_to 'Login', new_user_session_path, class: 'item' %>
    <%= link_to 'Sign-up', new_user_registration_path, class: 'item' %>
  <% end %>
</div>