config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'trips#index'

  resources :trips

  resources :locations do
    resources :addresses
  end

  get '/trip/:id/find_location/:id', to: 'trips#find_location', as: 'find_location'
  patch '/trip/:id/add_location/', to: 'trips#add_location', as: 'add_location'
  patch '/trip/:id/remove_location/:trip_id', to: 'trips#remove_location', as: 'remove_location'

end

app/models/location.rb
# == Schema Information
#
# Table name: locations
#
#  id                 :integer          not null, primary key
#  name               :string           not null
#  trip_id            :integer
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  image_file_name    :string
#  image_content_type :string
#  image_file_size    :integer
#  image_updated_at   :datetime
#
# Indexes
#
#  index_locations_on_trip_id  (trip_id)
#
# Foreign Keys
#
#  fk_rails_...  (trip_id => trips.id)
#

class Location < ApplicationRecord
  belongs_to :trip, optional: true
  has_one :address, dependent: :destroy
  has_attached_file :image, optional: true
  validates_attachment :image,
                     content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

 def self.find_location_not_on_trip
   Location.where('trip_id IS ?', nil)
 end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
before_action :set_location, only: [:show, :edit, :update, :destroy]

  def index
    @locations = Location.all
  end

  def show
    @hash = Gmaps4rails.build_markers(@location.address) do |address, marker|
      marker.lat address.latitude
      marker.lng address.longitude
    end
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)
    if @location.save
      redirect_to locations_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @location.update(location_params)
      redirect_to location_path(@location)
    else
      render :new
    end
  end

  def destroy
    @location.destroy
    redirect_to locations_path
  end

  private

  def set_location
    @location = Location.find(params[:id])
  end

  def location_params
    params.require(:location).permit(:name, :image)
  end

end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<h1><%= @location.id? ? 'Edit Location' : 'Add New Location' %></h1>

<div class="ui divider"></div>

<%= form_for @location, html: {class: "ui form"} do |f| %>

  <div class="four wide field">
    <p><strong><%= f.label :name %></strong></p>
    <%= f.text_field :name, required: true %>
  </div>

  <div class="ui hidden divider"></div>

  <div class="four wide field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="ui hidden divider"></div>

  <div class="action">
    <%= f.submit class: 'ui teal button' %>
  </div>

  <div class="ui hidden divider"></div>

<% end %>

<%= link_to 'Cancel', locations_path(@location), class: 'ui button red' %>

app/views/locations/edit.html.erb
<%= render 'form' %>

app/views/locations/index.html.erb
<div id="location-welcome">
  <h1>Travel Destinations</h1>
  <h2>
    <em>Browse from our selection or <%= link_to 'Create', new_location_path, id: 'create', class: 'ui teal inverted button' %> your own.</em>
  </h2>
</div>

<div class="ui divider hidden"></div>

<div class="ui grid">
    <div class "sixteen wide computer column">
      <div class="ui cards">
        <% @locations.each do |location| %>
          <div class="card">
            <div class="image">
              <%= check_if_image_is_present(location) %>
            </div>
            <div class="content">
              <div class="header">
                <%= link_to location.name, location_path(location.id), class: 'header', data: { turbolinks: false } %>
              </div>
              <div class="ui divider"></div>
              <% if location.address %>
                <div class="ui center aligned">
                  <%= display_full_address(location) %>
                </div>
              <% else %>
                <%= link_to 'Add New Address', new_location_address_path(location), class: 'ui green button' %>
              <% end %>
            </div>
            <div class="extra content">
              <%= link_to 'More Info', location_path(location.id), class: 'ui orange button', data: { turbolinks: false } %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/locations/new.html.erb
<%= render 'form'%>

app/views/locations/show.html.erb
<header id="welcome">
  <h1><%= @location.name %></h1>
  <% if @location.address %>
    <%= display_full_address(@location) %>
  <% else %>
    <%= link_to 'Add New Address', new_location_address_path(@location), class: 'ui green button' %>
  <% end %>
</header>

<br>

<%= link_to 'Edit Location', edit_location_path, class: 'ui teal button' %>
<%= link_to 'Delete Location', location_path(@location), method: :delete,
                                                   data: { confirm: 'Are you sure?'},
                                                   class: 'ui red button' %>

<div class="ui divider hidden"></div>

<div style='width: 500px;'>
  <div id="map" style='width: 500px; height: 250px;'></div>
</div>

<div class="ui divider hidden"></div>

<%= render 'shared/map' %>